server:
  port: 8086

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ethiomart.notification: INFO
